## NumPy - Playing with Numbers

#### NumPy lets you work with huge, multidimensional matrices and arrays. Along with that, it provides a gamut of high-level functions to perform mathematical operations on these structures

  ## Features of NumPy

           ndarray- n-dimensional arrays.
           Fourier transforms and shapes manipulation.
           Linear algebra and random number generation.
           Numpy is homogeneous Structure, i.e it contains elements of same types

In [1]:
## Import Numpy

import numpy as np

In [2]:
# 1D Array
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
# Shape (row*column) of a Array
a.shape

(3,)

In [6]:
# Total Number of elements
a.size

3

In [7]:
a.max

<function ndarray.max>

In [8]:
# Indexing in 1D array 
a[2]

3

In [9]:
# 2D Array (Rows. Column)
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# Shape of an array
b.shape

(3, 3)

In [12]:
# Total Number of Elements
b.size

9

In [13]:
# Maximum Element in Array
b.max()

9

In [14]:
# Minimum element of an array
b.min()

1

In [15]:
# Diagnol elements of an array
b.diagonal()

array([1, 5, 9])

In [16]:
b.data

In [17]:
# Cumulative Multiplication
b.cumprod()

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [18]:
# Cumulative Sum
b.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [19]:
## Sum of all Elements
b.sum()

45

In [20]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
## indexing on 2D Array
b[0,0] # Should retrun 1
b[1,0] # Should return 4
b[1,2] # Should retun 6
b[2,1] # should return 8

8

### Creation of Numpy Array

##### arange() Function
##### random.random () -- Random Class in Numpy
##### ones() -- To create an Array with all values 1
##### zeros () -- To create an Array with all values 0
##### eye() -- To Identity Matrix
##### full () -- Create a Matrix with Constant Value

In [22]:
# It is same like range function and creates 1D Array
c=np.arange(7)
c

array([0, 1, 2, 3, 4, 5, 6])

In [23]:
ran= np.random.random((3,3))
ran

array([[0.82501172, 0.04203795, 0.15267322],
       [0.45730343, 0.74753122, 0.71930667],
       [0.6960244 , 0.79336525, 0.24717153]])

In [24]:
ran1=np.random.random_sample((3,3))
ran1

array([[0.29617505, 0.08444438, 0.06244152],
       [0.5725597 , 0.64360511, 0.14375083],
       [0.5392162 , 0.31793264, 0.85265762]])

In [25]:
# Create an array selecting random number within low and high range for given size 
ran2=np.random.randint(10,100,size=(3,3))
ran2

array([[85, 15, 74],
       [36, 75, 90],
       [64, 96, 95]])

In [26]:
ran3=np.random.info
ran3

<module 'numpy.random.info' from 'C:\\Users\\shobhit.sharma\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\numpy\\random\\info.py'>

In [27]:
## Create 2D array with all elemenets as 1

one=np.ones((4,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
# 3D array with 4 (3x2) arrays all 0 elements

zero = np.zeros((4,3,2))
zero

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [29]:
# Size (2,3,4,5) --> it is a 4D array, and creates 4D array , each 4d conatins 2 3D Array, 
# and each 3D conatins 3 (4x5) 2D array

ran4= np.random.randint(20,80,size=(2,3,4,5))
ran4

array([[[[66, 60, 43, 74, 69],
         [52, 56, 55, 22, 74],
         [70, 58, 61, 57, 78],
         [59, 59, 34, 31, 70]],

        [[35, 33, 41, 22, 52],
         [63, 69, 37, 65, 66],
         [53, 52, 78, 23, 50],
         [55, 61, 32, 79, 51]],

        [[57, 78, 56, 23, 62],
         [72, 50, 66, 38, 74],
         [64, 48, 31, 70, 75],
         [65, 29, 25, 33, 34]]],


       [[[63, 59, 33, 40, 73],
         [74, 35, 37, 74, 41],
         [66, 32, 48, 34, 62],
         [72, 30, 44, 45, 75]],

        [[49, 48, 46, 29, 25],
         [61, 33, 34, 20, 47],
         [30, 73, 46, 39, 61],
         [49, 61, 70, 39, 40]],

        [[20, 49, 74, 78, 25],
         [52, 56, 78, 36, 76],
         [29, 74, 39, 55, 26],
         [60, 58, 21, 20, 53]]]])

In [30]:
# created identity Matrix , with each diagnoal element as 1 and rest are 0
eye1 = np.eye(4)
eye1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
# Create a sized array with constant value, i.e full() function will create (3x4) matrix with all values as 6

ful= np.full((3,4), 6)
ful

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [33]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
# gives the Dimension of an array 
b.ndim

2

### Indexing in Array

In [43]:
c=np.random.randint(20,100,size=(4,6))

In [44]:
c

array([[51, 22, 20, 51, 85, 96],
       [83, 59, 94, 50, 92, 86],
       [60, 64, 35, 92, 82, 35],
       [31, 54, 36, 95, 59, 32]])

In [45]:
c[1:3,2:4]

array([[94, 50],
       [35, 92]])

In [46]:
c[1:4,2:6]

array([[94, 50, 92, 86],
       [35, 92, 82, 35],
       [36, 95, 59, 32]])

In [47]:
c

array([[51, 22, 20, 51, 85, 96],
       [83, 59, 94, 50, 92, 86],
       [60, 64, 35, 92, 82, 35],
       [31, 54, 36, 95, 59, 32]])

In [50]:
## Conditional Formatting in Array
# Returns all elements > 50

c[c>50]

array([51, 51, 85, 96, 83, 59, 94, 92, 86, 60, 64, 92, 82, 54, 95, 59])

In [55]:
## Mathematical Operations on Arrays


In [56]:
a1=np.array([[1,2,3],[4,5,6]])
b1=np.array([[7,8,9],[10,11,12]])

In [58]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
b1

array([[ 7,  8,  9],
       [10, 11, 12]])

In [61]:
# Adding Element wise arrays

a1+b1

array([[ 8, 10, 12],
       [14, 16, 18]])

In [68]:
# Subtraction of 2 arrays
b1-a1
np.subtract(a1,b1)

array([[-6, -6, -6],
       [-6, -6, -6]])

In [76]:
# Multiplicati of 2 arrays (always element wise)

a1*b1

#np.multiply(a1,b1)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [66]:
b1/a1

#np.divide(a1,b1)

array([[7. , 4. , 3. ],
       [2.5, 2.2, 2. ]])

In [77]:
# Mathematical operations liek SQRT, Log, Exp all can be perfomred on Arrays

np.sqrt(a1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [79]:
# Sum all elements of an array

np.sum(a1)

21

In [82]:
# Transposition from Row to Column or from Column to Row
 
    # Transposed 2x3 matrix to 3x2

np.array(a1).T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Stacking of mulitple arrays
     2 types of stacking available, Horizontal and Vertical 
     Stacking can be perfomred on mulitple arrays 

In [71]:
np.vstack((a1,b1))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [72]:
c1=np.array([[13,14,15],[16,17,18]])

In [73]:
c1

array([[13, 14, 15],
       [16, 17, 18]])

In [74]:
np.vstack((b1,a1,c1))

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [13, 14, 15],
       [16, 17, 18]])

In [75]:
np.hstack((c1,a1,b1))

array([[13, 14, 15,  1,  2,  3,  7,  8,  9],
       [16, 17, 18,  4,  5,  6, 10, 11, 12]])